name: Build & Publish library [DEV]
on:
  push:
    branches: [ dev ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[SKIP CI]')"
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 — Checking the repository.
        uses: actions/checkout@v2

      - name: Step 2 — Installing the Node.
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Step 3 — Install dependencies.
        run: yarn install --production=true --user

      - name: Step 4 — Build the library.
        run: yarn run build

      - name: Step 5 — Generate new version.
        run: npm version --git-tag-version=false $(jq --raw-output '.version' package.json).t$(date +%s).$(git rev-parse --short HEAD)

      - name: Step 6 — Publish the library.
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: "public"
          tag: "dev"

